// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDncIOEnzqT8aSShO7UTSGaJ_PHf_MUhM',
    appId: '1:874338099633:web:7b965e7c8a9b3cdabedd90',
    messagingSenderId: '874338099633',
    projectId: 'fire-cli-1',
    authDomain: 'fire-cli-1.firebaseapp.com',
    storageBucket: 'fire-cli-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpGeyjIF0XrS14FaK_wiXYqSgHRjKELZw',
    appId: '1:874338099633:android:176cedcbc5665879bedd90',
    messagingSenderId: '874338099633',
    projectId: 'fire-cli-1',
    storageBucket: 'fire-cli-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvO_GyYrOeEXNPd8ss6Kkylp71owzTLU8',
    appId: '1:874338099633:ios:aab9641c87bea330bedd90',
    messagingSenderId: '874338099633',
    projectId: 'fire-cli-1',
    storageBucket: 'fire-cli-1.appspot.com',
    iosBundleId: 'com.example.myFirebaseFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDncIOEnzqT8aSShO7UTSGaJ_PHf_MUhM',
    appId: '1:874338099633:web:f0008623ffb5f07dbedd90',
    messagingSenderId: '874338099633',
    projectId: 'fire-cli-1',
    authDomain: 'fire-cli-1.firebaseapp.com',
    storageBucket: 'fire-cli-1.appspot.com',
  );
}
